frontend:
  - changed-files:
      - any-glob-to-any-file:
          - app/**
          - components/**
          - hooks/**
          - lib/**

backend:
  - changed-files:
      - any-glob-to-any-file:
          - server/**
          - drizzle/**

deploy:
  - changed-files:
      - any-glob-to-any-file:
          - dist/**
          - netlify.toml
          - .github/workflows/**
