create table public.class_a_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  slug text not null unique,
  title text not null,
  status text not null default 'planning'
    check (status in ('planning','scheduled','live','completed','cancelled')),
  platform text not null default 'google_meet'
    check (platform in ('google_meet')),
  timezone text not null default 'Asia/Dhaka',
  starts_at timestamptz,
  ends_at timestamptz,
  join_url text,
  calendar_event_id text,
  recording_url text,
  transcript_url text,
  analysis_status text not null default 'pending'
    check (analysis_status in ('pending','ready','failed')),
  analysis_summary jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint class_a_sessions_time_check
    check (starts_at is null or ends_at is null or ends_at > starts_at)
);

alter table public.class_a_sessions enable row level security;
revoke all on table public.class_a_sessions from anon, authenticated;

create table public.class_a_session_enrollments (
  id uuid primary key default extensions.gen_random_uuid(),
  registration_id bigint not null references public.class_a_registrations(id) on delete cascade,
  session_id uuid not null references public.class_a_sessions(id) on delete cascade,
  status text not null default 'confirmed'
    check (status in ('confirmed','attended','cancelled')),
  confirmed_at timestamptz not null default now(),
  pass_code_hash text not null unique,
  pass_code_last4 text not null,
  attended_at timestamptz,
  attendance_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (registration_id, session_id)
);

create index class_a_session_enrollments_session_status_idx
  on public.class_a_session_enrollments(session_id, status, confirmed_at desc);

alter table public.class_a_session_enrollments enable row level security;
revoke all on table public.class_a_session_enrollments from anon, authenticated;

create table public.class_a_live_checkin_codes (
  id uuid primary key default extensions.gen_random_uuid(),
  session_id uuid not null references public.class_a_sessions(id) on delete cascade,
  code_hash text not null unique,
  code_last4 text not null,
  opens_at timestamptz not null,
  closes_at timestamptz not null,
  invalidated_at timestamptz,
  created_at timestamptz not null default now(),
  constraint class_a_live_checkin_window_check check (closes_at > opens_at)
);

create index class_a_live_checkin_codes_session_window_idx
  on public.class_a_live_checkin_codes(session_id, opens_at, closes_at);

alter table public.class_a_live_checkin_codes enable row level security;
revoke all on table public.class_a_live_checkin_codes from anon, authenticated;

create table public.class_a_session_attendance_evidence (
  id bigint generated by default as identity primary key,
  enrollment_id uuid not null references public.class_a_session_enrollments(id) on delete cascade,
  registration_id bigint not null references public.class_a_registrations(id) on delete cascade,
  session_id uuid not null references public.class_a_sessions(id) on delete cascade,
  evidence_type text not null
    check (evidence_type in ('portal_open','join_click','live_code','meet_report','staff_code')),
  evidence_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index class_a_session_attendance_evidence_lookup_idx
  on public.class_a_session_attendance_evidence(session_id, enrollment_id, evidence_at desc);

alter table public.class_a_session_attendance_evidence enable row level security;
revoke all on table public.class_a_session_attendance_evidence from anon, authenticated;

create table public.class_a_session_notifications (
  id bigint generated by default as identity primary key,
  enrollment_id uuid not null references public.class_a_session_enrollments(id) on delete cascade,
  registration_id bigint not null references public.class_a_registrations(id) on delete cascade,
  session_id uuid not null references public.class_a_sessions(id) on delete cascade,
  notification_type text not null
    check (notification_type in (
      'registration_confirmation',
      'calendar_invite',
      'reminder_24h',
      'reminder_6h',
      'room_open',
      'post_class_followup'
    )),
  delivery_policy text not null default 'whatsapp_then_email',
  due_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending','processing','sent','failed','skipped')),
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  external_ref text,
  created_at timestamptz not null default now(),
  unique (enrollment_id, notification_type)
);

create index class_a_session_notifications_due_idx
  on public.class_a_session_notifications(status, due_at)
  where status in ('pending','failed');

alter table public.class_a_session_notifications enable row level security;
revoke all on table public.class_a_session_notifications from anon, authenticated;

create or replace function private.class_a_queue_session_notifications(
  p_enrollment_id uuid
) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_enrollment public.class_a_session_enrollments%rowtype;
  v_session public.class_a_sessions%rowtype;
begin
  select * into v_enrollment
  from public.class_a_session_enrollments
  where id = p_enrollment_id;

  if v_enrollment.id is null then return; end if;

  select * into v_session
  from public.class_a_sessions
  where id = v_enrollment.session_id;

  if v_session.id is null then return; end if;

  insert into public.class_a_session_notifications(
    enrollment_id, registration_id, session_id, notification_type, due_at
  ) values (
    v_enrollment.id, v_enrollment.registration_id, v_session.id,
    'registration_confirmation', now()
  )
  on conflict (enrollment_id, notification_type) do nothing;

  if v_session.status in ('scheduled','live') and v_session.starts_at is not null then
    insert into public.class_a_session_notifications(
      enrollment_id, registration_id, session_id, notification_type, due_at
    ) values (
      v_enrollment.id, v_enrollment.registration_id, v_session.id,
      'calendar_invite', now()
    )
    on conflict (enrollment_id, notification_type) do nothing;

    if v_session.starts_at - interval '24 hours' > now() then
      insert into public.class_a_session_notifications(
        enrollment_id, registration_id, session_id, notification_type, due_at
      ) values (
        v_enrollment.id, v_enrollment.registration_id, v_session.id,
        'reminder_24h', v_session.starts_at - interval '24 hours'
      )
      on conflict (enrollment_id, notification_type) do update
        set due_at = excluded.due_at
        where public.class_a_session_notifications.status in ('pending','failed');
    end if;

    if v_session.starts_at - interval '6 hours' > now() then
      insert into public.class_a_session_notifications(
        enrollment_id, registration_id, session_id, notification_type, due_at
      ) values (
        v_enrollment.id, v_enrollment.registration_id, v_session.id,
        'reminder_6h', v_session.starts_at - interval '6 hours'
      )
      on conflict (enrollment_id, notification_type) do update
        set due_at = excluded.due_at
        where public.class_a_session_notifications.status in ('pending','failed');
    end if;

    if v_session.starts_at - interval '15 minutes' > now() then
      insert into public.class_a_session_notifications(
        enrollment_id, registration_id, session_id, notification_type, due_at
      ) values (
        v_enrollment.id, v_enrollment.registration_id, v_session.id,
        'room_open', v_session.starts_at - interval '15 minutes'
      )
      on conflict (enrollment_id, notification_type) do update
        set due_at = excluded.due_at
        where public.class_a_session_notifications.status in ('pending','failed');
    end if;

    insert into public.class_a_session_notifications(
      enrollment_id, registration_id, session_id, notification_type, due_at
    ) values (
      v_enrollment.id, v_enrollment.registration_id, v_session.id,
      'post_class_followup',
      coalesce(v_session.ends_at, v_session.starts_at + interval '2 hours') + interval '10 minutes'
    )
    on conflict (enrollment_id, notification_type) do update
      set due_at = excluded.due_at
      where public.class_a_session_notifications.status in ('pending','failed');
  end if;
end;
$$;

revoke all on function private.class_a_queue_session_notifications(uuid) from public, anon, authenticated;

create or replace function private.class_a_enrollment_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.class_a_queue_session_notifications(new.id);
  return new;
end;
$$;

revoke all on function private.class_a_enrollment_notification_trigger() from public, anon, authenticated;

create trigger class_a_session_enrollment_notifications
after insert or update of session_id on public.class_a_session_enrollments
for each row execute function private.class_a_enrollment_notification_trigger();

create or replace function private.class_a_session_refresh_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  if tg_op = 'UPDATE' then
    update public.class_a_sessions set updated_at = now() where id = new.id;
  end if;

  for v_id in
    select e.id from public.class_a_session_enrollments e where e.session_id = new.id
  loop
    perform private.class_a_queue_session_notifications(v_id);
  end loop;
  return new;
end;
$$;

revoke all on function private.class_a_session_refresh_trigger() from public, anon, authenticated;

create trigger class_a_session_refresh_notifications
after insert or update of status, starts_at, ends_at, join_url on public.class_a_sessions
for each row execute function private.class_a_session_refresh_trigger();

create or replace function public.class_a_register_online(
  p_full_name text,
  p_phone text,
  p_email text,
  p_skill_level text default null,
  p_source text default 'class-a-online-masterclass-v1'
)
returns table(
  outcome text,
  registration_id bigint,
  enrollment_id uuid,
  confirmed_at timestamptz,
  pass_code text,
  pass_code_last4 text,
  session_id uuid,
  session_status text,
  session_title text,
  session_starts_at timestamptz,
  session_ends_at timestamptz,
  session_timezone text,
  session_join_url text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := btrim(coalesce(p_full_name,''));
  v_phone text;
  v_email text := lower(btrim(coalesce(p_email,'')));
  v_skill text := nullif(btrim(coalesce(p_skill_level,'')), '');
  v_source text := btrim(coalesce(p_source,'class-a-online-masterclass-v1'));
  v_registration public.class_a_registrations%rowtype;
  v_session public.class_a_sessions%rowtype;
  v_enrollment public.class_a_session_enrollments%rowtype;
  v_code text;
  v_hex text;
begin
  v_phone := public.class_a_normalize_phone(p_phone);

  if char_length(v_name) < 2 or char_length(v_name) > 120 then
    raise exception 'invalid_name' using errcode = '22023';
  end if;
  if char_length(v_phone) < 6 or char_length(v_phone) > 40 then
    raise exception 'invalid_phone' using errcode = '22023';
  end if;
  if char_length(v_email) < 5 or char_length(v_email) > 200 or position('@' in v_email) = 0 then
    raise exception 'invalid_email' using errcode = '22023';
  end if;

  select * into v_registration
  from public.class_a_registrations r
  where r.program='masterclass' and (r.email=v_email or r.phone=v_phone)
  order by r.id desc
  limit 1;

  if v_registration.id is null then
    insert into public.class_a_registrations(program, full_name, phone, email, skill_level, source, record_kind)
    values ('masterclass', v_name, v_phone, v_email, v_skill, v_source, 'genuine')
    returning * into v_registration;
  elsif v_registration.record_kind <> 'genuine' then
    return query
      select 'excluded_record'::text, v_registration.id, null::uuid, null::timestamptz,
             null::text, null::text, null::uuid, null::text, null::text,
             null::timestamptz, null::timestamptz, null::text, null::text;
    return;
  else
    update public.class_a_registrations
      set full_name=v_name,
          phone=v_phone,
          email=v_email,
          skill_level=coalesce(v_skill, skill_level)
    where id=v_registration.id
    returning * into v_registration;
  end if;

  select * into v_session
  from public.class_a_sessions s
  where s.status in ('planning','scheduled')
    and (s.starts_at is null or s.starts_at > now())
  order by
    case when s.status='scheduled' then 0 else 1 end,
    s.starts_at nulls last,
    s.created_at
  limit 1;

  if v_session.id is null then
    return query
      select 'no_session'::text, v_registration.id, null::uuid, null::timestamptz,
             null::text, null::text, null::uuid, null::text, null::text,
             null::timestamptz, null::timestamptz, null::text, null::text;
    return;
  end if;

  select * into v_enrollment
  from public.class_a_session_enrollments e
  where e.registration_id=v_registration.id and e.session_id=v_session.id;

  if v_enrollment.id is not null then
    return query
      select 'already_registered'::text, v_registration.id, v_enrollment.id,
             v_enrollment.confirmed_at, null::text, v_enrollment.pass_code_last4,
             v_session.id, v_session.status, v_session.title, v_session.starts_at,
             v_session.ends_at, v_session.timezone, v_session.join_url;
    return;
  end if;

  loop
    v_hex := upper(encode(extensions.gen_random_bytes(6), 'hex'));
    v_code := 'CLA-' || substr(v_hex,1,6) || '-' || substr(v_hex,7,6);
    begin
      insert into public.class_a_session_enrollments(
        registration_id, session_id, status, confirmed_at, pass_code_hash, pass_code_last4
      ) values (
        v_registration.id, v_session.id, 'confirmed', now(),
        encode(extensions.digest(v_code, 'sha256'), 'hex'), right(v_code,4)
      )
      returning * into v_enrollment;
      exit;
    exception when unique_violation then
      select * into v_enrollment
      from public.class_a_session_enrollments e
      where e.registration_id=v_registration.id and e.session_id=v_session.id;
      if v_enrollment.id is not null then exit; end if;
    end;
  end loop;

  return query
    select 'confirmed'::text, v_registration.id, v_enrollment.id,
           v_enrollment.confirmed_at, v_code, right(v_code,4),
           v_session.id, v_session.status, v_session.title, v_session.starts_at,
           v_session.ends_at, v_session.timezone, v_session.join_url;
end;
$$;

revoke all on function public.class_a_register_online(text,text,text,text,text) from public;
grant execute on function public.class_a_register_online(text,text,text,text,text) to anon, authenticated;

create or replace function public.class_a_get_session_pass(p_code text)
returns table(
  outcome text,
  full_name text,
  enrollment_id uuid,
  enrollment_status text,
  attended_at timestamptz,
  session_id uuid,
  session_status text,
  session_title text,
  session_starts_at timestamptz,
  session_ends_at timestamptz,
  session_timezone text,
  session_join_url text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_code text := upper(btrim(coalesce(p_code,'')));
begin
  return query
  select
    'ok'::text,
    r.full_name,
    e.id,
    e.status,
    e.attended_at,
    s.id,
    s.status,
    s.title,
    s.starts_at,
    s.ends_at,
    s.timezone,
    s.join_url
  from public.class_a_session_enrollments e
  join public.class_a_registrations r on r.id=e.registration_id
  join public.class_a_sessions s on s.id=e.session_id
  where e.pass_code_hash=encode(extensions.digest(v_code,'sha256'),'hex')
  limit 1;

  if not found then
    return query select 'invalid_code'::text, null::text, null::uuid, null::text,
      null::timestamptz, null::uuid, null::text, null::text, null::timestamptz,
      null::timestamptz, null::text, null::text;
  end if;
end;
$$;

revoke all on function public.class_a_get_session_pass(text) from public;
grant execute on function public.class_a_get_session_pass(text) to anon, authenticated;

create or replace function public.class_a_record_session_signal(
  p_code text,
  p_signal text
)
returns table(outcome text, enrollment_id uuid, session_id uuid, recorded_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_enrollment public.class_a_session_enrollments%rowtype;
  v_signal text := lower(btrim(coalesce(p_signal,'')));
  v_now timestamptz := now();
begin
  if v_signal not in ('portal_open','join_click') then
    return query select 'invalid_signal'::text, null::uuid, null::uuid, null::timestamptz;
    return;
  end if;

  select * into v_enrollment
  from public.class_a_session_enrollments e
  where e.pass_code_hash=encode(extensions.digest(upper(btrim(coalesce(p_code,''))),'sha256'),'hex');

  if v_enrollment.id is null then
    return query select 'invalid_code'::text, null::uuid, null::uuid, null::timestamptz;
    return;
  end if;

  insert into public.class_a_session_attendance_evidence(
    enrollment_id, registration_id, session_id, evidence_type, evidence_at
  ) values (
    v_enrollment.id, v_enrollment.registration_id, v_enrollment.session_id, v_signal, v_now
  );

  return query select 'recorded'::text, v_enrollment.id, v_enrollment.session_id, v_now;
end;
$$;

revoke all on function public.class_a_record_session_signal(text,text) from public;
grant execute on function public.class_a_record_session_signal(text,text) to anon, authenticated;

create or replace function public.class_a_issue_live_code(
  p_session_id uuid,
  p_staff_key text,
  p_minutes integer default 20
)
returns table(outcome text, live_code text, opens_at timestamptz, closes_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expected_hash text;
  v_staff_hash text := encode(extensions.digest(coalesce(p_staff_key,''), 'sha256'), 'hex');
  v_hex text;
  v_code text;
  v_open timestamptz := now();
  v_close timestamptz;
begin
  select value_hash into v_expected_hash
  from private.class_a_config
  where key='checkin_staff_key_sha256';

  if v_expected_hash is null or v_staff_hash <> v_expected_hash then
    return query select 'invalid_staff_key'::text, null::text, null::timestamptz, null::timestamptz;
    return;
  end if;

  if not exists (
    select 1 from public.class_a_sessions s
    where s.id=p_session_id and s.status in ('scheduled','live')
  ) then
    return query select 'invalid_session'::text, null::text, null::timestamptz, null::timestamptz;
    return;
  end if;

  v_close := v_open + make_interval(mins => greatest(5, least(coalesce(p_minutes,20),60)));

  loop
    v_hex := upper(encode(extensions.gen_random_bytes(4), 'hex'));
    v_code := 'BUILD-' || substr(v_hex,1,6);
    begin
      insert into public.class_a_live_checkin_codes(
        session_id, code_hash, code_last4, opens_at, closes_at
      ) values (
        p_session_id,
        encode(extensions.digest(v_code,'sha256'),'hex'),
        right(v_code,4),
        v_open,
        v_close
      );
      exit;
    exception when unique_violation then
    end;
  end loop;

  return query select 'issued'::text, v_code, v_open, v_close;
end;
$$;

revoke all on function public.class_a_issue_live_code(uuid,text,integer) from public;
grant execute on function public.class_a_issue_live_code(uuid,text,integer) to anon, authenticated;

create or replace function public.class_a_verify_live_attendance(
  p_pass_code text,
  p_live_code text
)
returns table(
  outcome text,
  enrollment_id uuid,
  registration_id bigint,
  session_id uuid,
  attended_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_enrollment public.class_a_session_enrollments%rowtype;
  v_live public.class_a_live_checkin_codes%rowtype;
  v_now timestamptz := now();
begin
  select * into v_enrollment
  from public.class_a_session_enrollments e
  where e.pass_code_hash=encode(extensions.digest(upper(btrim(coalesce(p_pass_code,''))),'sha256'),'hex')
  for update;

  if v_enrollment.id is null then
    return query select 'invalid_pass'::text, null::uuid, null::bigint, null::uuid, null::timestamptz;
    return;
  end if;

  select * into v_live
  from public.class_a_live_checkin_codes c
  where c.session_id=v_enrollment.session_id
    and c.code_hash=encode(extensions.digest(upper(btrim(coalesce(p_live_code,''))),'sha256'),'hex')
    and c.invalidated_at is null
    and v_now between c.opens_at and c.closes_at
  order by c.created_at desc
  limit 1;

  if v_live.id is null then
    return query select 'invalid_or_expired_live_code'::text, v_enrollment.id,
      v_enrollment.registration_id, v_enrollment.session_id, v_enrollment.attended_at;
    return;
  end if;

  if v_enrollment.attended_at is null then
    update public.class_a_session_enrollments
      set status='attended', attended_at=v_now, attendance_source='live_code', updated_at=v_now
    where id=v_enrollment.id
    returning class_a_session_enrollments.attended_at into v_enrollment.attended_at;

    insert into public.class_a_session_attendance_evidence(
      enrollment_id, registration_id, session_id, evidence_type, evidence_at,
      metadata
    ) values (
      v_enrollment.id, v_enrollment.registration_id, v_enrollment.session_id,
      'live_code', v_now, jsonb_build_object('live_code_id',v_live.id)
    );
  end if;

  return query select
    case when v_enrollment.attended_at=v_now then 'attended'::text else 'already_attended'::text end,
    v_enrollment.id, v_enrollment.registration_id, v_enrollment.session_id, v_enrollment.attended_at;
end;
$$;

revoke all on function public.class_a_verify_live_attendance(text,text) from public;
grant execute on function public.class_a_verify_live_attendance(text,text) to anon, authenticated;

insert into public.class_a_sessions(slug,title,status,platform,timezone)
values (
  'class-0-online-next',
  'CLASS[Λ] — The 0.01% Builders Masterclass',
  'planning',
  'google_meet',
  'Asia/Dhaka'
)
on conflict (slug) do nothing;

comment on table public.class_a_sessions is
  'Canonical CLASS[Λ] live-session schedule and post-session artifact state. Server-owned; public clients use controlled RPCs.';
comment on table public.class_a_session_enrollments is
  'Per-session enrollment and pass state. Separates recurring masterclass attendance from the person-level registration record.';
comment on table public.class_a_session_attendance_evidence is
  'Evidence ledger for online attendance signals. portal_open/join_click are signals only; live_code/meet_report/staff_code may support verified attendance.';
comment on table public.class_a_session_notifications is
  'Automation outbox for confirmation, calendar, reminders, room-open and post-class follow-up. Delivery workers must preserve approval and channel policy.';
